### ISSUE TITLE
iOS CI: ConnectionFailureTests.testConnectionFailureSurfacesErrorNotConnecting flaky on hosted runner (stays .connecting past the 5s poll)

### ISSUE THREAD

**Issue by jirathip-k** [jirathip-dev/corral#179]
Observed on `ios.yml` workflow_dispatch run https://github.com/jirathip-dev/corral/actions/runs/32675575767 (branch `g173/ios-demo-boundary-tests` @ f42128b, the second stability run for #173):

```
FleetNotifierTests.swift:3214: error: -[FleetNotifierTests.ConnectionFailureTests testConnectionFailureSurfacesErrorNotConnecting] : failed - connection failure must set .error, not connecting
Test Case '...testConnectionFailureSurfacesErrorNotConnecting' failed (5.364 seconds).
```

The test uses its own `FailingStreamURLProtocol` mock (independent of the `DeterministicDriveURLProtocol` harness changed in PR #177) and polls `store.connectionState` for up to 5s expecting `.error`; on this run the state stayed `.connecting` for the full window. The first run on the same head (https://github.com/jirathip-dev/corral/actions/runs/32675391707) and all earlier runs passed this test, and `TappableDriveSafetyTests` (#173) passed on both runs — so this is a separate, intermittent runner-timing defect in the connection-failure surfacing path or its mock, not caused by #173.

Not fixed in #177 (scope discipline). Needs its own root-cause pass: either the mock's failure is not delivered before the poll deadline on a loaded runner, or `FleetStore.connect` delays the `.error` transition (e.g. a reconnect/backoff step) longer than the test allows — the fix must not be a longer sleep.

Filed by orch-corral while gating #173.

**Comment by jirathip-k** [comment]
orch-corral: Opus R3 adversarial verdict on `2f7f790` is **FAIL / REQUEST-CHANGES**. It proved `Task.detached` only relocates the MainActor hop: under a ~6s synthetic backlog parent fails at 6.016s (`neverStarted`) and head at 6.011s (`neverLanded`); reverting the production edit leaves 174/174 green, so that edit has no regression coverage. Assertions and the 5s bound remained intact; baseline full suite and 10x repetition were green.

Fix round R4 is now running in the original worktree under registry-mandated Codex `gpt-5.6-luna` max (`impl-g179-r4-1`). Brief requires re-grounding in the real connection/cancellation/actor contract, preserving the 5s semantic assertion, correcting disproven docs/comments and teardown order, adding RED coverage, >=10x targeted simulator stability, full suite, then re-review by the same Opus reviewer. Hosted `ios.yml` remains mandatory before merge.

**Comment by jirathip-k** [comment]
R4 implementation is pushed at `7ab7b7f` (fix commit `9fb87f2`): the disproven detached-task mechanism was removed, teardown now synchronizes real callback/stream termination, the 5-second bound and semantic assertions remain unchanged, focused tests passed 40/40 across ten runs, the full simulator suite passed 174/174, and deleting the real error callback produced the expected RED mutation failure. The same Opus reviewer that issued the R3 FAIL is now adversarially re-reviewing the exact final head.

**Comment by jirathip-k** [comment]
Merged and evidenced on `main`.

- PR: #198 (squash-merged)
- Main commit: `6cefaa2efbaee03884c48f2fead0ba39244e54b7`
- Exact reviewed branch head: `7ab7b7f8ef471b1b5d4686a2c021efab524c1709` (tree-identical to fix commit `9fb87f2`)
- Same Opus reviewer that issued R3 FAIL returned PASS after R4
- Independent local review: 174/174 full tests; 80/80 stress repetitions; deletion of `onConnectionError` and `onConnected` each produced targeted RED failures; cancellation-first teardown was observed through stream-task exit
- Five-second bound unchanged; every original semantic assertion preserved
- Hosted PR CI green: Rust workspace https://github.com/jirathip-dev/corral/actions/runs/32731868670 and secret scan https://github.com/jirathip-dev/corral/actions/runs/32731868621
- Hosted iOS stability run 1 green: https://github.com/jirathip-dev/corral/actions/runs/32731913829
- Hosted iOS stability run 2 green: https://github.com/jirathip-dev/corral/actions/runs/32732954039

The second hosted run is material evidence because the original flake appeared on the second stability run. No assertion was weakened and no sleep/deadline was increased.
